-- Seed: roles table.
--
-- Auto-generated by scripts/db-export-seed.sh from the dev DB.
-- Applied automatically by scripts/deploy-bootstrap.sh on every deploy
-- AFTER schema.sql and any migrations/*.sql have run.
--
-- Idempotent: ON CONFLICT DO NOTHING. Existing rows on the target DB
-- are never overwritten — this seed only ADDS missing rows. Safe to
-- re-apply on every deploy.
--
-- To regenerate this file: ./scripts/db-export-seed.sh
-- To wipe a specific user from prod: hand-edit + DELETE statement here,
-- or call /api/admin/users DELETE then re-export.

INSERT INTO roles (email, role, created_by) VALUES ('huy@locallife.asia', 'admin', 'bootstrap')
  ON CONFLICT (email) DO NOTHING;
