#!/usr/bin/env bash
# Export the local DB roles table into a versioned SQL seed file.
#
# Workflow:
#   1. Make role changes via /admin/users (or psql) on this dev machine.
#   2. Run this script. It rewrites apps/web/db/seed/roles.sql.
#   3. git add + commit + push. PR review shows the data change.
#   4. On server deploy, scripts/deploy-bootstrap.sh applies the seed
#      after the schema/migrations. ON CONFLICT DO NOTHING means existing
#      rows on prod (e.g. real human accounts) are NEVER overwritten —
#      the seed only ADDS missing rows.
#
# Usage:
#   ./scripts/db-export-seed.sh                # default — exclude *-dev@locallife.asia
#   ./scripts/db-export-seed.sh --include-dev  # include synthetic dev rows too
#
# Env: DATABASE_URL (read from .env.local automatically).
set -euo pipefail

INCLUDE_DEV=false
case "${1:-}" in
  --include-dev) INCLUDE_DEV=true ;;
  -h|--help)
    sed -n '2,/^$/p' "$0" | sed 's/^# //; s/^#//'
    exit 0
    ;;
esac

cd "$(dirname "$0")/.."

if [[ -f .env.local ]]; then
  set -a; . ./.env.local; set +a
fi

DB_URL="${DATABASE_URL:?DATABASE_URL not set — fill .env.local first}"

if ! command -v psql >/dev/null 2>&1; then
  echo "ERROR: psql client not installed." >&2
  echo "  macOS:  brew install libpq && brew link --force libpq" >&2
  echo "  Linux:  sudo apt install postgresql-client" >&2
  exit 1
fi

OUT="apps/web/db/seed/roles.sql"
mkdir -p "$(dirname "$OUT")"

WHERE=""
if [[ "$INCLUDE_DEV" == "false" ]]; then
  # Exclude synthetic dev users (created by NextAuth dev credentials provider).
  # Pattern: <role>-dev@<ALLOWED_DOMAIN> as defined in lib/auth.ts.
  WHERE="WHERE email NOT LIKE '%-dev@%'"
fi

# Header
cat > "$OUT" <<'HEADER'
-- Seed: roles table.
--
-- Auto-generated by scripts/db-export-seed.sh from the dev DB.
-- Applied automatically by scripts/deploy-bootstrap.sh on every deploy
-- AFTER schema.sql and any migrations/*.sql have run.
--
-- Idempotent: ON CONFLICT DO NOTHING. Existing rows on the target DB
-- are never overwritten — this seed only ADDS missing rows. Safe to
-- re-apply on every deploy.
--
-- To regenerate this file: ./scripts/db-export-seed.sh
-- To wipe a specific user from prod: hand-edit + DELETE statement here,
-- or call /api/admin/users DELETE then re-export.

HEADER

# Body — generated INSERT statements
COUNT=0
while IFS='|' read -r email role created_by; do
  [[ -z "$email" ]] && continue
  esc_email="${email//\'/\'\'}"
  esc_role="${role//\'/\'\'}"
  if [[ -z "$created_by" ]]; then
    cb_sql="NULL"
  else
    esc_cb="${created_by//\'/\'\'}"
    cb_sql="'$esc_cb'"
  fi
  printf "INSERT INTO roles (email, role, created_by) VALUES ('%s', '%s', %s)\n  ON CONFLICT (email) DO NOTHING;\n" \
    "$esc_email" "$esc_role" "$cb_sql" >> "$OUT"
  COUNT=$((COUNT + 1))
done < <(psql "$DB_URL" -At -F"|" --no-align -c "
  SELECT email, role, COALESCE(created_by, '')
  FROM roles
  $WHERE
  ORDER BY role, email
")

echo "[db-export-seed] wrote $OUT — $COUNT row(s)"
if [[ "$INCLUDE_DEV" == "false" && $COUNT -eq 0 ]]; then
  echo "[db-export-seed] (no non-dev rows found — pass --include-dev to include synthetic accounts)"
fi
